### ISSUE TITLE
wiredep broken when targeting bootstrap 3.3.5

### ISSUE THREAD

**Issue by pkskelly** [johnpapa/gulp-patterns#104]
Just an FYI, the latest version of bootstrap breaks the wiredep functionality and does not properly inject the bootstap.css file when you get to the "Removing Scripts and Styles From the Main HTML" section.

The fix for me was to simply target bootstrap 3.3.2 directly. Removing the ~ from the bower.json file entry and running bower install again forced 3.3.2. 

Awesome course!

**Comment by johnpapa** [comment]
fixed with 85681bf7525445cf90e8d84c6c792adc8189a1cf

**Comment by johnpapa** [comment]
Thanks ... no need to hard code Instead I override it and tell bootstrap to add it back in. See the commit above.

**Comment by pkskelly** [comment]
overrides!  I just keep learning more stuff!! :-)  Thanks.
