### ISSUE TITLE
Running gulp commands is changing source files

### ISSUE THREAD

**Issue by nareshbhatia** [johnpapa/gulp-patterns#70]
Great project - I am finding it very useful to learn gulp best practices.

It seems that running gulp commands is changing source files. For example:

1. `gulp serve-dev` is changing `src/client/index.html`.
2. `gulp serve-specs` is changing `src/client/specs.html`.

Is this intentional?

**Comment by johnpapa** [comment]
yep

**Comment by nareshbhatia** [comment]
Ah, I see that it is the wiredep injection that's doing it. Personally it bothers me that it moves the lines around everytime it runs - makes me feel that I have changed something in source.

**Comment by wardbell** [comment]
That is a PITA. I'd like to see them fix that.

**Comment by johnpapa** [comment]
consistency would be nice. open a github issue with it.
