### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by igorlino** [johnpapa/gulp-patterns#84]
Hi John,

I have done some related-work recently for localization support.

* It was quite nice implemented using (https://angular-gettext.rocketeer.be/).  
* Extended gulpfile.js/gulpconfig.js: added a task for extracting translations and a task for compiling the translations.
* Added a /localization/ directory containing: template.pot and locale like en_US.po, etc.

There was a minor problem with making translations dynamically available, since they need a 1 time compilation. So I generated them anyway in the /build/ directory, and make the server recognize them.

I could provide the changes I did, even if they are not optimal.

Cheers,
Igor

**Comment by johnpapa** [comment]
happy to see them here

**Comment by igorlino** [comment]
Alright. I did not manage to create a clean pull request.

But here is the commit: 

https://github.com/igorlino/gulp-patterns/commit/b68bf75c92c1da61981fb34d97c6f5a235436cdc
