### ISSUE TITLE
Adding LiveReload?

### ISSUE THREAD

**Issue by dmitriz** [johnpapa/gulp-patterns#97]
Are there plans to include LiveReload?

Here is a simple script example:
https://github.com/dmitriz/gulp-automation

**Comment by johnpapa** [comment]
Browser sync is in there and does the same thing and more. 







On Thu, Apr 30, 2015 at 8:06 PM -0700, "Dmitri Zaitsev" <notifications@github.com> wrote:












Are there plans to include LiveReload?



Here is a simple script I came up with:

https://github.com/dmitriz/gulp-automation

**Comment by dmitriz** [comment]
I am sure BrowserSync can be very powerful and do great things.

But if all you need is to (reliably) reload your files in browser, I find it hard to justify downloading 25MB package. 

Also the project doesn't seem to be mature yet as it sometimes silently fails to reload without any error messages.

**Comment by johnpapa** [comment]
Haven't had any issues whileLive reload has given me issues. Feel free to use what you prefer but I see no need to change this repo 
Thanks

Sent from Outlook




On Thu, Apr 30, 2015 at 8:55 PM -0700, "Dmitri Zaitsev" <notifications@github.com> wrote:












I am sure BrowserSync can be very powerful and do great things.



But if all you need is to (reliably) reload your files in browser, I find it hard to justify downloading 25MB package. 



Also the project doesn't seem to be mature yet as it sometimes silently fails to reload without any error messages.
